bot:
  prefix: "!"
  token: !ENV "token"
  staff_roles: [748554755265134635, 809311700560904201, "baby, ako na lang kasi"]

database:
  name: !ENV "db_name"
  host: !ENV "db_host"
  user: !ENV "db_user"
  password: !ENV "db_pass"