bot:
  prefix: "pph-"
  token: !ENV "token"

database:
  database:
  name: !ENV "db_name"
  host: !ENV "db_host"
  user: !ENV "db_user"
  password: !ENV "db_pass"
  port: !ENV "db_port"


api:
  api_ninja: !ENV "api_ninja"

guild:
  staff_roles: [ 1062998739012296795 ]
  dev_help_forum: 1020260384638259210
  log_channel: 1076405709916344360

logger:
  log_channel: 1076405709916344360
  log_level: "DEBUG"
