bot:
  prefix: "pph-"
  token: !ENV "token"
  staff_roles: [1062998739012296795]

database:
  name: !ENV "db_name"
  host: !ENV "db_host"
  user: !ENV "db_user"
  password: !ENV "db_pass"
  port: !ENV "db_port"

ai:
  token: !ENV "llm_token"
  base_url: !ENV "llm_base_url"
  model: !ENV "llm_model"

api:
  api_ninja: !ENV "api_ninja_key"

guild:
  staff_roles: [1062998739012296795] # [748554755265134635]
  dev_help_forum: !ENV "dev_help_forum_id"
  log_channel: !ENV "log_channel"

logger:
  log_channel: !ENV "log_channel"
  log_level: "DEBUG"
