# Purpose: Build and push Docker image to DockerHub
# SSH on remote server and run docker commands to update running bot

name: Docker CICD

on:
  push:
    branches:
      - "main"

env:
  USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.USERNAME }}/progphil-bot:latest
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        
      -
        name: Configure SSH Key permissions
        
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/pph.key
          chmod 600 ~/.ssh/pph.key
          cat >>~/.ssh/config <<END
          
      - 
        name: Deploy on Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker stop progphil-bot || true && docker rm progphil-bot || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/progphil-bot:latest
            docker run --env token=${{secrets.PPH_TEST_SERVER_BOT_TOKEN }} -it -d ${{ secrets.DOCKERHUB_USERNAME }}/progphil-bot:latest
